### ISSUE TITLE
enable blocking network access to network(s)

### ISSUE THREAD

**Issue by TomasTomecek** [packit/sandcastle#11]
https://blog.openshift.com/accessing-external-services-using-egress-router/

depends on #10 

can we set the egress policy per pod within a project?

**Comment by TomasTomecek** [comment]
also https://docs.openshift.com/container-platform/3.6/admin_guide/managing_networking.html#admin-guide-networking-networkpolicy

**Comment by lachmanfrantisek** [comment]
Stale-bot does not understand the config?

https://github.com/packit-service/sandcastle/blob/06b329556d25c03c1f6c781967673872a6d8a9a1/.github/stale.yml#L5-L10

**Comment by jpopelka** [comment]
The bot closed it even it had not been marked `stale` so I think he just had a bad day or something.
