### ISSUE TITLE
consider using libguestfs for sandboxing

### ISSUE THREAD

**Issue by TomasTomecek** [packit/sandcastle#13]
@stefwalter gave us an idea to run the untrusted commands inside an emulated environment (e.g. qemu). Since the platform would need to support such a thing, we should also take a look if libguestfs tooling would be able to do the job.

When investigating this, check out how cockpit is doing this.

**Comment by jscotka** [comment]
Not sure If I understand it well, to use `libguestfs` tools. There are 2 ways how command could be executed on images via libguesfs tools:
 - need support at least for user virtualization. (might be problem inside current openshift I think?)
   - run it inside running image direclty after start (like ssh execute to system after boot)
   - run it as part of system service when staring system (moreless similar to cloud-init) 
 - commads are run on FS level on target image. It is more less something like `chroot` into image, so probably still possible to access host system. (not secure)

**Comment by csomh** [comment]
Please re-open it if you consider it still relevant.
