### ISSUE TITLE
error: tmp/tmp.XYZ/t.tar.gz no such file or directory

### ISSUE THREAD

**Issue by jpopelka** [packit/sandcastle#42]
- https://sentry.io/organizations/red-hat-0p/issues/1380802387
- https://sentry.io/organizations/red-hat-0p/issues/1280080644
- https://sentry.io/organizations/red-hat-0p/issues/1359895131

**Comment by TomasTomecek** [comment]
```
httplib POST https://copr.fedorainfracloud.org/api_3/build/create/upload [504]

Gateway Timeout

Request is not in JSON format, there is probably a bug in the API code.
```

what?!

**Comment by TomasTomecek** [comment]
> Error from server (Forbidden): pods "docker-io-usercont-sandcastle-20191127-143943513496" is forbidden: User "system:serviceaccount:packit-stg:importimager" cannot get pods in the namespace "packit-stg-sandbox": no RBAC policy matched

misconfigured stage? or a message from local deployment?

**Comment by TomasTomecek** [comment]
```
exception while initiating WS Client: (0)
Reason: [Errno 113] No route to host
```
long time no see

**Comment by TomasTomecek** [comment]
so, it seems that we need change something in the sandcastle code so that the execution is halted and the real error bubbles up

**Comment by jpopelka** [comment]
> User "system:serviceaccount:packit-stg:importimager" cannot get pods in the namespace "packit-stg-sandbox"

I haven't seen that but it looks like a misconfiguration because that service account should be used only in the `import-images` CronJob.

**Comment by jpopelka** [comment]
> Request is not in JSON format, there is probably a bug in the API code.

This one is not related, that's https://github.com/packit-service/packit-service/issues/316

**Comment by jpopelka** [comment]
I've seen more of them recently:
- https://sentry.io/organizations/red-hat-0p/issues/1431910066
- https://sentry.io/organizations/red-hat-0p/issues/1427949505

**Comment by TomasTomecek** [comment]
The symptoms are still the same:
* `Reason: [Errno 113] No route to host`
* `[Errno 113] No route to host`

in both new cases

**Comment by TomasTomecek** [comment]
Looking at related issues:
* https://github.com/openshift/origin/issues/19597
* https://github.com/openshift/origin/issues/19044

Seems like we'd need the ops team to look into it.

**Comment by TomasTomecek** [comment]
I'm closing this one since we are not seeing these anymore (due to the implemented retry mechanism)
